# Generated by Django 4.1.5 on 2023-01-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakedbybri', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='recipe',
            field=models.TextField(default=''),
        ),
    ]
