# Generated by Django 4.1.7 on 2023-03-26 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bakedbybri', '0002_post_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='ingredients',
            field=models.ManyToManyField(blank=True, related_name='post_list', to='bakedbybri.ingredients'),
        ),
    ]
